### PR TITLE
Use date formatting in homepage name 

### PR DESCRIPTION
**Pull request by kzhovn**
Addresses #14 . I've tested it and everything seems to work fine with my setup.

Also, my autoformatter seems to have eaten some of your trailing whitespace. Happy to revert that if it's a problem.

### CODE REVIEW

**Comment by kzhovn** [comment]
Also, from here #15 is a trivial change and I'm happy to implement it, just didn't want to dump several things on you at once.

**Comment by mirnovov** [comment]
Thanks! Yeah, they've both easy changes, I just don't have the time to do them rn.
I'm happy to merge your changes if you squash all your commits into one, as it seems like a single logical change to me.

**Comment by kzhovn** [comment]
And done (without #15 at the moment, as soon as I said "trivial change" I realized I didn't quite understand how I wanted it to behave if workspaces are selected on desktop).

**Comment by mirnovov** [comment]
I meant all of #14, it makes sense to do #15 as a separate commit. Personally, I'd just disable the mobile homepage feature if workspaces are enabled, but if you want to do something else, I'm fine with it.

**Pull request merged**
